# Server configuration
server:
  port: ":8080"

# Kong Reference
kong:
  host: "http://127.0.0.1:8001"
  consumer_request: "/consumers/"
  jwt_request: "/consumers/%s/jwt"

# Jaeger
jaeger:
  host: "localhost"
  port: "6831"

#Mysql
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password:
  database: userdb

#Search
search_limit: 10