# Server configuration
server:
  port: ":8080"

# Kong Reference
kong:
  host: "http://getclass_kong:8001"
  consumer_request: "/consumers/"
  jwt_request: "/consumers/%s/jwt"

# Jaeger
jaeger:
  host: "jaeger"
  port: "6831"

#Mysql
mysql:
  host: mysql
  port: 3306
  user: root
  password:
  database: userdb

#Search
search_limit: 1